theme: jekyll-theme-minimal
url: https://neilboyd.github.io/me

# make the collapsible sections work
# https://github.com/github/jekyll-commonmark-ghpages
markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
